name: aua_questions_app
description: "A new Flutter project."
publish_to: "none"

version: 2.15.0+14

environment:
  sdk: ">=3.3.0-152.0.dev <4.0.0"

dependencies:
  appwrite: ^15.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  flutter_stepindicator: ^0.1.7
  flutter_svg: ^2.0.9
  get: ^4.7.2
  google_mobile_ads: ^4.0.0
  http: ^1.3.0
  lottie: ^3.0.0
  onesignal_flutter: ^5.0.4
  package_info_plus: ^8.3.0
  percent_indicator: ^4.2.3
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  syncfusion_flutter_gauges: ^23.2.7
  url_launcher: ^6.2.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/AUAlogo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  win32: ^5.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/medivineway.png

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
